App base/learn-rails/config/routes.rb
Rails.application.routes.draw do
 root 'homes#index'
  
 get 'apps' => 'homes#apps' 
 get '/contacts' => 'homes#contacts'
 get '/test' => 'homes#test'


 get 'acronyms/app'=> 'acronyms#app' 
 get 'imagefinder/app'=> 'imagefinder#app' 
 get 'blackjack/app' => 'blackjack#app'

  

end

App base/learn-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

App base/learn-rails/app/controllers/acronyms_controller.rb
class AcronymsController < ApplicationController

def app
  @result = ""

  if params[:phrase].present?
  
  @result = (params[:phrase].split(/[\s ,\-,\,]/).map{ |x| x[0].capitalize unless x[0] == nil })#.join
  @result = (@result.map {|word| word << "."}).join

  end


end

end

App base/learn-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

App base/learn-rails/app/controllers/blackjack_controller.rb
  
class BlackjackController < ApplicationController
    
    def app
        if (session[:deck_id] == nil) 
            response = Faraday.get("https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1")
            json = JSON.parse(response.body)
            session[:deck_id] = json["deck_id"]

            session[:playercards] = draw_two(session[:deck_id])
            session[:compcards] = draw_one(session[:deck_id])
        end
        
        if (session[:deck_id] != nil)    
            @total_player = get_total(session[:playercards])
            @total_computer = get_total(session[:compcards])
        end

        if (params[:hit]) then hit end
        if (params[:restart]) then restart end
        if (params[:stay]) then comps_turn end

        
    end

    private

    def draw_two(deck_id)
        response = Faraday.get("https://deckofcardsapi.com/api/deck/#{deck_id}/draw/?count=2")
        json = JSON.parse(response.body)
        cards = json["cards"]
    end

    def draw_one(deck_id)
        response = Faraday.get("https://deckofcardsapi.com/api/deck/#{deck_id}/draw/?count=1")
        json = JSON.parse(response.body)
        cards = json["cards"]
    end

    def get_value(card)
        case card
        when "KING", "QUEEN", "JACK"
            value=10
        when "ACE"
            value=11
        else
            value=card.to_i
        end
    end

    def get_total(cards)
        total = 0
        cards.each do |card|
            total += get_value(card["value"])
        end
        return total
    end
    
    def hit   
        new_card = draw_one(session[:deck_id])
        session[:playercards].push(new_card[0])
        @total_player = get_total(session[:playercards])
    end

    def restart
        session[:playercards] = nil
        session[:compcards] = nil
        session[:deck_id] = nil
        redirect_to action: "app"
    end

    def comps_turn
        while @total_computer < 17 do
            card = draw_one(session[:deck_id])
            session[:compcards].push(card[0])
            @total_computer = get_total(session[:compcards])
        end
        outcome
    end

    def outcome
        if @total_player > @total_computer
            @outcome = "You Win!"
        elsif @total_player < @total_computer
            @outcome = "You Lose!"
        else
            @outcome = "Draw!"
        end
    end
end

App base/learn-rails/app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def index
        @show = true
        @topics = ["Rails Views" , "Routing" , "MVC Convention in Rails"]
    end 

    def apps
    end

    def contacts
        if params[:name].present?
        @name = params[:name]
        @email = params[:email]
        @input_statement = "Hi #{@name} Thanks for getting in touch. we have sent a correspondence email to #{@email} " 
        end
    end

    def test
        @array = ["mike" , "ann" , "raj"]
    end


end

App base/learn-rails/app/controllers/imagefinder_controller.rb
  
class ImagefinderController < ApplicationController
  def app
    if params[:keywords].present?
      @keywords = params[:keywords]
      @keywords2 = @keywords.split
      @keywords3 = ""
      n = 0
      @keywords2.each do |i|
        @keywords3 += i
        n += 1
        break if n == @keywords2.length
        @keywords3 += ", "
      end
    else
      @keywords3 = ""
    end
  end
end

App base/learn-rails/app/helpers/acronyms_helper.rb
module AcronymsHelper
end

App base/learn-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

App base/learn-rails/app/helpers/imagefinder_helper.rb
module ImagefinderHelper
end

App base/learn-rails/app/views/acronyms/app.html.erb
<!DOCTYPE html>
<head>

  <meta charset="utf-8">
  <title>Acronym App</title>
  <%= stylesheet_link_tag 'mane1.css' %>
  <%= stylesheet_link_tag 'mane2.css' %>
</head>
<body>

<div class="container w-container">



<center>
<%= link_to "Home" , root_path , id:"node1b" ,class: "button w-button" %>
</br>
</br>
<h1>Acronyms app</h1>
</br>


        <%= form_tag("/acronyms/app", method: "get") do %>

          <%= label_tag(:phrase, "Phrase:") %>
          <%= text_field_tag(:phrase) %>
          </br>
          <%= label_tag(:rs, "Result:") %>
          <input type="text" id="rs" name="rs" value="<%= @result %>" readonly>
          </br>
          <%= submit_tag("Search") %>
          
          
        <% end %>
       
        
      
        </center></div>

  
</body>
</html>




     

      

App base/learn-rails/app/views/blackjack/app.html.erb
<body class="blackjack">
    <div class="rules">
        <h3>Rules:</h3>
        <ul>
            <li>Dealer stands on 17+</li>
            <li>An ace is only worth 11</li>
        </ul>
    </div>
    <h1>Computers Cards:</h1>
    <div class="card-container">
        <% session[:compcards].each do |card|%>
        <div class="card">
            <h3><%= card["value"].capitalize%> of <%= card["suit"].capitalize%> </h3>
            <%= image_tag(card["images"]["png"])%>
        </div>
        <% end%>
    </div>
    <h3>Total: <%= @total_computer%></h3>
    <% if @total_computer == 21%>
        <h3>Blackjack!</h3>
    <% end%>

    <h1>Your Cards:</h1>   
    <div class="card-container">
        <% session[:playercards].each do |card|%>
        <div class="card">
            <h3><%= card["value"].capitalize%> of <%= card["suit"].capitalize%> </h3>
            <%= image_tag(card["images"]["png"])%>
        </div>
        <% end%>
    </div>
    <h3>Total: <%= @total_player%></h3>
    <% if @total_player == 21%>
        <h3>Blackjack! You Win!</h3>
    <% elsif @total_player > 21%>
        <h3>You Lose!</h3>
    <% elsif @total_computer == 21%>
        <h3>You Lose!</h3>
    <% elsif @total_computer > 21%>
        <h3>You Win!</h3>
    <% elsif @total_computer >= 17%>
        <h3><%=@outcome%></h3>
    <% else%>
        <%= form_with url: "/blackjack/app", method: :get do |form| %>
            <%= form.button :Hit, name: "hit", value: true %>
            <%= form.button :Stay, name: "stay", value: true %>
        <% end%>
    <% end%>
    <%= form_with url: "/blackjack/app", method: :get do |form| %>
        <%= form.button :Restart, name: "restart", value: true%>
    <%end%>
</body>

App base/learn-rails/app/views/homes/apps.html.erb
<head>
  <meta charset="utf-8">
  <title>Apps</title>
  <%= stylesheet_link_tag 'mane1.css' %>
  <%= stylesheet_link_tag 'mane2.css' %>
</head>
<body class="body">
  <!-- <h1 class="heading">Let&#x27;s Learn Rails</h1>
  <div class="w-layout-grid grid-2">
  <%= link_to "Home" , root_path , id:"node1b" ,class: "button w-button" %>
  <%= link_to "Contact Us" , contacts_path , id:"node1c" ,class: "button w-button" %>
  </div> -->
  <div class="w-row" style = "margin: 50px">
    <div class="basic-column w-col w-col-4 w-col-stack">
      <div class="tag-wrapper">
        <div class="product-card">
          <div class="product-card-image product-card-1"></div>
          <div class="product-card-description">
            <div>
              <div class="tagline tagline-promo-40">Acronym Maker</div>
              <h3 class="product-name-title">creates Acronyms for you.<span class="text-span"></span></h3>
            </div>
            <div class="price-wrapper"></div>
            <%= link_to "Select" , acronyms_app_path  , class:"button-2 w-button" %>
          </div>
        </div>
      </div>
      <u style="color: white"><p style="color: white ; margin-left: 10px ; font-family: Lucida Console;"> Educator General - Melb flex </p></u>
    </div>
    <div class="basic-column w-col w-col-4 w-col-stack">
      <div class="tag-wrapper">
        <div class="product-card">
          <div class="product-card-image product-card-2"></div>
          <div class="product-card-description">
            <div>
              <div class="tagline tagline-promo-40">Image Finder</div>
              <h3 class="product-name-title">Type in a tag to find image</h3>
            </div>
            <div class="price-wrapper"></div>
<a href=<%= imagefinder_app_path %> class="button-2 w-button">Select</a>
          </div>
        </div>
      </div>
      <u style="color: white"><p style="color: white ; margin-left: 10px ; font-family: Lucida Console;"> Daniel Hinton - Melb flex </p></u>
    </div>
    <div class="basic-column w-col w-col-4 w-col-stack">
      <div class="tag-wrapper">
        <div class="product-card">
          <div class="product-card-image product-card-3"></div>
          <div class="product-card-description">
            <div>
              <div class="tagline tagline-promo-40">Blackjack</div>
              <h3 class="product-name-title">Blackjack simulator</h3>
            </div>
            <div class="price-wrapper"></div>
            <%= link_to "Select" , blackjack_app_path  , class:"button-2 w-button" %>
          </div>
        </div>
      </div>
      <u style="color: white"><p style="color: white ; margin-left: 10px ; font-family: Lucida Console;"> Daniel Walters - Melb flex </p></u>
    </div>
  </div>
</body>

App base/learn-rails/app/views/homes/contacts.html.erb
<head>

  <meta charset="utf-8">
  <title>Contact Us</title>
  <%= stylesheet_link_tag 'mane1.css' %>
  <%= stylesheet_link_tag 'mane2.css' %>
</head>
<body>
  <h1 class="heading">Contact Page</h1>
  <div class="w-layout-grid grid-2">
  <%= link_to "Home" , root_path , id:"node1b" ,class: "button w-button" %>
  <%= link_to "Our Apps" , apps_path , id:"node1c" ,class: "button w-button" %>
    
  </div> -->
  <h3 class="heading-2">Hi! Please leave your contact info with us </h3>
  <h3 class="heading-2">We will connect with you shortly... </h3>
  
  <div class="container w-container">

  <%= form_tag("/contacts", method: "get") do %>
    <%= label_tag(:q, "Name:") %>
    <%= text_field_tag(:name) %>
    <%= label_tag(:q, "Email:") %>
    <%= text_field_tag(:email) %>
    <%= submit_tag("Submit") %>
  <% end %>

  <h2> <%= @input_statement %> </h2>
  </div>

  
    
  <div class="container w-container"></div>
  
</body>

App base/learn-rails/app/views/homes/index.html.erb
<head>

  <meta charset="utf-8">
  <title>Home</title>
  <%= stylesheet_link_tag 'mane1.css' %>
  <%= stylesheet_link_tag 'mane2.css' %>
</head>
<body>
  <!--<h1 class="heading">Let&#x27;s Learn Rails</h1>
  <div class="w-layout-grid grid-2">
  <%= link_to "Our Apps" , apps_path , id:"node1b" ,class: "button w-button" %>
  <%= link_to "Contact Us" , contacts_path , id:"node1c" ,class: "button w-button" %>
    
  </div> -->
  <h2 class="heading-2">Welcome<br> to your first &#x27;Rails&#x27; website</h2>
  <div class="container w-container"></div>
  <div class="columns w-row">
    <div class="w-col w-col-6">
      <p class="paragraph">Today we will learn...</p>
    </div>
    <% if @show %>
    <div class="w-col w-col-6">
      <ul role="list" class="list-2">
       <% @topics.each do |topic| %> 
        <li class="list-item"> <%= topic  %> </li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>
</body>

App base/learn-rails/app/views/homes/test.html.erb
<h1> ERB practice page </h1>

<!-- @array.each do |element| 
    puts element
end -->

<% @array.each do |element| %>
    <h3> <%= element  %> </h3>
    <% end %>

    </br>
    </br>
    </br>

    <%5.times do -%> 
        <h4> <%= "liftoff!" %> </h4>
    <% end -%>
    

App base/learn-rails/app/views/homes/test2.html.erb
<h1> Hello </h1>

App base/learn-rails/app/views/imagefinder/app.html.erb
<div class="body-container">

  <h1>ImageFinder</h1>

  <%= form_with url: "app", class: "keyword-form", method: :get do |form| %>
    <%= form.label :keywords, "Enter Keywords:" %>
    <%= form.text_field :keywords, class: "text-field" %>
    <%= form.submit "Enter", class: "submit-button" %>
  <% end %>

  <h2>Keywords: <%= @keywords3.titleize %></h2>

    <div class="random-image">
      <img src="https://source.unsplash.com/1600x900/?<%=@keywords3%>" alt="img">
    </div>

</div>

App base/learn-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1 class="heading">Let&#x27;s Learn Rails</h1>
  <div class="w-layout-grid grid-2">
  <%= link_to "Our Apps" , apps_path , id:"node1b" ,class: "button w-button" %>
  <%= link_to "Contact Us" , contacts_path , id:"node1c" ,class: "button w-button" %>
    
  </div>
    <%= yield %>
  </body>
</html>